
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
show_downloads: [true]
github:
  zip_url: https://github.com/spektor56/OpenpilotToolkit/releases/download/1.8.0/OpenpilotToolkit.7z
  tar_url: https://github.com/spektor56/OpenpilotToolkit/releases/download/1.1.0/com.spektor56.openpilottoolkitandroid-Signed.apk
